# Generated by Django 5.1.7 on 2025-03-24 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviesmodel',
            name='movies_link',
            field=models.URLField(max_length=512),
        ),
    ]
